name: Build Docs

on:
  push:
    branches: [ master ]

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2

      - name: Install dependencies
        run: poetry install

      - name: Build docs with pdoc
        run: |
          export PYTHONPATH=src
          poetry run pdoc llm_harness --docformat google --output-dir docs