name: Docs
on:
  push:
    branches: [ master ]
permissions:
  contents: write  # Need write permission to commit back to the repo
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: true
jobs:
  deploy:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_ACTIONS_DOCS_WORKFLOW }}  # Use your secret name here
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version-file: "pyproject.toml"
    - name: Install the project
      run: uv sync --all-extras --group docs
    - name: Create docs
      run: uv run pdoc overhaul --docformat google --output-dir docs/
      
    # Set up Git identity for committing
    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
      env:
        GITHUB_TOKEN: ${{ github.token }}
        
    # Commit and push changes back to master
    - name: Commit documentation changes
      run: |
        git add docs/
        git commit -m "Update documentation" || echo "No changes to commit"
        git push origin master

    # Deploy to GitHub Pages (if you also want GitHub Pages)
    - name: Upload docs artifacts
      uses: actions/upload-pages-artifact@v3
      with:
        path: docs
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
